### ISSUE TITLE
Missing Category UE 5.3.2

### ISSUE THREAD

**Issue by DevgodHk** [getnamo/Llama-Unreal#13]
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(286): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(289): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(292): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(296): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(300): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(304): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(307): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(310): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(314): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(319): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
Plugins\Llama-Unreal\HostProject\Plugins\Llama\Source\LlamaCore\Public\LlamaComponent.h(329): Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.

**Comment by getnamo** [comment]
pull latest, added missing categories (untested) here: https://github.com/getnamo/Llama-Unreal/commit/bb4e1a59f71e80698350becdab4183ffa7fc1e0c
